            ##### USERS SERVICE #####

### GET ALL USERS ###
GET http://localhost:3000/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM3OTEyNzI2LCJleHAiOjE2Mzc5MTYzMjZ9.SQL65DKNpq7Hcso2EzvVJT_PMRSgCkms6zYr7pySvL0

### CREATE USER ###
POST http://localhost:3000/api/user HTTP/1.1
Content-Type: application/json

{
    "firstname": "Jane",
    "lastname": "Doe",
    "email": "jadoe@gmail.com",
    "username": "jadoe",
    "password": "password",
    "role": "user"
}

### GET PROFILE ###
GET http://localhost:3000/api/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM3OTEyNzI2LCJleHAiOjE2Mzc5MTYzMjZ9.SQL65DKNpq7Hcso2EzvVJT_PMRSgCkms6zYr7pySvL0

### LOGIN USER ###
POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "jadoe@gmail.com",
    "password": "password"
}


### UPDATE USER ###
PUT http://localhost:3000/api/user HTTP/1.1
Content-Type: application/json

{
    "role": "user"
}

### ADMIN TEST ###
GET http://localhost:3000/api/admintest HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM3ODIwMTk2LCJleHAiOjE2Mzc4MjM3OTZ9.Muu0Qm8xBFAs3OTYOVK8ybuJm804vXDZWFymkki_oO8

### USER TEST ###
GET http://localhost:3000/api/usertest HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM3OTAwNjg2LCJleHAiOjE2Mzc5MDQyODZ9.yJKBa4DdqwtRGAUjcweISOXDTAFFqhVGvwenetxh6KQ

### DELETE USER ###
DELETE http://localhost:3000/api HTTP/1.1



            ##### TODO SERVICE #####

### GET ALL ###
GET http://localhost:3000/api/todo/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4

### GET SINGLE ###
GET http://localhost:3000/api/todo/ea3d3aa5-714c-49b8-be4a-cf2265ea96d6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4

### POST SINGLE ###
POST http://localhost:3000/api/todo/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4
Content-Type: application/json

{
    "done": false,
    "details": "What I need in my kitchen and house",
    "dueDate": "2021-12-06"
}


### UPDATE SINGLE ###
PUT http://localhost:3000/api/todo/ea3d3aa5-714c-49b8-be4a-cf2265ea96d6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4
Content-Type: application/json

{
    "done": true
}

### DELETE SINGLE ###
DELETE http://localhost:3000/api/todo/aa602511-ce7d-456a-962f-c13844b38a54 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4


            ##### BLOG SERVICE #####

### GET ALL ###
GET http://localhost:3000/api/blog HTTP/1.1

### POST SINGLE ###
POST http://localhost:3000/api/blog HTTP/1.1
Content-Type: application/json

{
    "author": "Jane Doe",
    "title": "Lorem Dipsum4",
    "content": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit quia consequuntur eius dolorem tenetur architecto explicabo reprehenderit ullam enim qui placeat ipsa, minima totam eos maxime earum rem. Dolore, fuga."
}

### GET SINGLE ###
GET http://localhost:3000/api/blog/0b07e59c-e9db-4ffd-99a3-917183088c52 HTTP/1.1

### UPDATE SINGLE ###
PUT http://localhost:3000/api/blog/0b07e59c-e9db-4ffd-99a3-917183088c52 HTTP/1.1
Content-Type: application/json

{
    "title": "Chill Fool",
    "author": "Jane Doe",
    "content": "I just made this up, its shitty I know"
}

### DELETE SINGLE ###
DELETE http://localhost:3000/api/blog/11532759-8acc-4be4-9115-1ed6749916db HTTP/1.1


###
GET http://localhost:3000/api/api/list-aliases HTTP/1.1


            ##### NOTE SERVICE #####

### GET ALL ###
GET http://localhost:3000/api/note HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4

### GET SINGLE ###
GET http://localhost:3000/api/note/0c234fe7-7a09-4c0b-b3b2-9697fd23984a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4

### POST SINGLE ###
POST http://localhost:3000/api/note HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4
Content-Type: application/json

{
    "title": "Hello World",
    "description": "Always the first",
    "notes": "Always the first point in any programming language"
}


### UPDATE SINGLE ###
PUT http://localhost:3000/api/note/0c234fe7-7a09-4c0b-b3b2-9697fd23984a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4
Content-Type: application/json

{
    "notes": "We need to change that narrative"
}


### REMOVE SINGLE ###
DELETE http://localhost:3000/api/note/f7a29b4c-7e6c-4eec-b69b-5ca7b9508a0f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphZG9lIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjM4MDM2NTA2LCJleHAiOjE2MzgwNDAxMDZ9.ashS3RHTn2JXK_VoKH3nJMtak68xA5CjYoXuX-RzcS4
